CREATE TABLE IF NOT EXISTS NOBEL_WIN (
  YEAR INTEGER,
  SUBJECT TEXT,
  WINNER TEXT,
  COUNTRY TEXT,
  CATEGORY TEXT
);



INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
  (1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
  (1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
  (1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
  (1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
  (1972, 'LITERTURE', 'BERNARD KELSON', 'GERMANY', 'ECONOMIST'),
  (1972, 'ECONOMICS', 'JOSEPH', 'RUSSIAN', 'ECONOMIST'),
  (1973, 'BIOLOGY', 'PHILLIPS', 'USA', 'PRIME MINISTER'),
  (1980, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT'),
  (1981, 'PHYSIOLOGY', 'HANNAH', 'HUNGRY', 'SCIENTIST'),
  (1975, 'PHYSICS','PETER', 'CHILIE', 'SCIENTIST');


SELECT *
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';